### ISSUE TITLE
Tag: Anchor使用時の閉じるボタンとの併用は推奨しない

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#112]
aタグを使うということは画面遷移をともなうので、画面遷移できる領域をみずから取り除けるような処理は不必要に複雑なので入れるべきではない、という話をした

**Comment by Hidetaro7** [comment]
> aタグを使うということは画面遷移をともなうので、画面遷移できる領域をみずから取り除けるような処理は不必要に複雑なので入れるべきではない、という話をした

この書きっぷりをちょっと工夫すると良いが、意図としてはこのままの内容で記載する。
