### ISSUE TITLE
プロダクトのBI（ブランド・アイデンティティ）を作成する

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#114]
関連 #109 

作成したロゴをリポジトリに含めたら完了

**Comment by Tomo416** [comment]
ロゴのカラーについては別issueを立てた　＃168

**Comment by Hidetaro7** [comment]
![JumpuUI-logo](https://user-images.githubusercontent.com/281424/182607616-5425f446-d9c8-42c6-ad37-ab3f1367cb3e.svg)

> 作成したロゴをリポジトリに含めたら完了

リポジトリの保存場所はどこがいいでしょう？

**Comment by knokmki612** [comment]
とりあえず `/docs` とかですかね

**Comment by Hidetaro7** [comment]
docsディレクトリに追加、さらにREADME.mdにロゴを配置したのでクローズ
