### ISSUE TITLE
Junpu UIのロゴのカラーについて

### ISSUE THREAD

**Issue by Tomo416** [tuqulore/jumpu-ui#168]
Junpu UIのロゴのカラーについて

Junpu UI自体、Tailwind CSSをベースにしているのでこちらも水色がいいのではないかなと思いました。
#0097F6
また、順風→風を思わせる色→水色
としても良さそうかなと思いました。

コントラスト比は通常文字はNGですが、ロゴとして使うので巨大文字・太文字がクリアできていれば良いかなと思っていますがどうでしょう？

![image](https://user-images.githubusercontent.com/57510486/155646322-41d7ba7f-cbec-43ab-83d2-14e68badf92a.png)
![image](https://user-images.githubusercontent.com/57510486/155646341-7efa6d5e-6fb0-4fd6-8eab-4d3150dfa8b9.png)

_Originally posted by @Tomo416 in https://github.com/tuqulore/jumpu-ui/issues/114#issuecomment-1050476131_

**Comment by Hidetaro7** [comment]
> コントラスト比は通常文字はNGですが、ロゴとして使うので巨大文字・太文字がクリアできていれば良いかなと思っていますがどうでしょう？

通常コントラスト比のチェック対象はテキストだと思うので、ロゴ画像はある程度の大きさを確保していればよいと思います。

色に関しては異論ないです。（形についてはここでは議論しないという意味で）

**Comment by knokmki612** [comment]
> Junpu UI自体、Tailwind CSSをベースにしているのでこちらも水色がいいのではないかなと思いました。
> #0097F6

どこを参照した色でしょう

たとえばTailwindCSSのロゴからピックしたものは #38bdf8 で、

https://tailwindcss.com/docs/customizing-colors#default-color-palette のカラーパレットとしては Sky の400番になるようです

**Comment by knokmki612** [comment]
> 通常コントラスト比のチェック対象はテキストだと思うので、ロゴ画像はある程度の大きさを確保していればよいと思います。

今回のロゴはテキスト自体がロゴになっているような構成なので、文字としてのコントラストを気にされているのかなと思いました

**Comment by Tomo416** [comment]
#0097F6
こちらはTailwindCSSのロゴからピックした色を、コントラスト比を見ながら調整した色です。

**Comment by Tomo416** [comment]
ということもあり、個人的には気に入っている色なのですが、こちらはいかがでしょうか

**Comment by knokmki612** [comment]
あえて変える理由はないと思いました。ただ #169 の内容によってはまた考える機会がくる可能性もあると思っています

**Comment by Hidetaro7** [comment]
色はブルー（#0097F6）に決まりました
