### ISSUE TITLE
Jumpu UIのロゴの形について

### ISSUE THREAD

**Issue by Tomo416** [tuqulore/jumpu-ui#169]
年末だかのYORIAIでこのロゴの形で良さそうという話になったが、改めて。
個人的にはこの形が親しみやすく読みやすく良いと思う。
今はフチがついていないが、つけるべきかどうか、つけるとしたら何色が良いかなどありましたら。
![image](https://user-images.githubusercontent.com/57510486/155646322-41d7ba7f-cbec-43ab-83d2-14e68badf92a.png)

**Comment by knokmki612** [comment]
ロゴの制作過程についておしえてもらいたいです

たとえば

- 何かベースとなるフォントはあるのか
- あるとすれば変更した箇所はあるのか
- 余白の調整などは文字ごとにされた状態であるのか

**Comment by Tomo416** [comment]
こちらは皆で画面を見ながら作ったと思うのですが私の方では把握ができていないため、 @Hidetaro7 お願いいたします

>ロゴの制作過程についておしえてもらいたいです
>たとえば
>何かベースとなるフォントはあるのか
>あるとすれば変更した箇所はあるのか
>余白の調整などは文字ごとにされた状態であるのか

**Comment by Hidetaro7** [comment]
ロゴに関してはみんなで取り組むという話があったと思いますので、この形状にこだわらなくてよいと考えています。
一般的なサンセリフ体のボールドであってもよいと思うのですが、「順風」なのでカジュアルで風や雲をイメージした形状が気になったので試験的につくって見てみようと思ったくらいです。

> 何かベースとなるフォントはあるのか

Arista 2.0 Alternate

> あるとすれば変更した箇所はあるのか

ありません

> 余白の調整などは文字ごとにされた状態であるのか

トラッキング処理を少し加えているだけです

**Comment by Tomo416** [comment]
ありがとうございます。
以前、皆で見ながらゴシック体でも試して比べたかと思いますが、ゴシック体の場合はインパクトはありますが少し固い印象を持ちました。
形にかんしてはクセが強すぎず読みやすく、丸みを帯びていて親しみやすさもあり、Jumpu UIのツールの柔軟性（デザイナーだけではなくエンジニアも使うことができるという柔軟性）にもマッチしていると個人的には感じていて、こちらの案が良いかなと思いました。

**Comment by knokmki612** [comment]
Arista 2.0 Alternate フォントをベースに考えるので異存はないです

**Comment by Hidetaro7** [comment]
> また、フチはつけず（袋文字にせず）でもいいかなと思いました。

一応、比較をしておきましょう。

<img width="662" alt="image" src="https://user-images.githubusercontent.com/281424/162124708-c95e41ad-1f9a-4c98-95ca-f8f2e239e3ab.png">

**Comment by Hidetaro7** [comment]
形状修正点

- Jの文字が前回だと判別するに少しむずかしいというユニバーサルデザインで指摘されそうな形を修正
- Mの文字の真ん中の縦棒が短く、これも少し長くし、可読しやすいように修正

**Comment by knokmki612** [comment]
作業しているFigmaってどこでしたでしょうか（私も触ってみたく）

**Comment by Tomo416** [comment]
フチ無しでもいいかなと思いましたが、微調整いただいた一番下がキャッチーで見やすい印象を受けました。
これはIllustratorデータでしたっけ？

**Comment by Hidetaro7** [comment]
イラレデータですが、くのっちが持ってないよね、多分。
Figmaに貼ってみます！

**Comment by Hidetaro7** [comment]
https://www.figma.com/file/Lo0RCwldNBkcYFnl075Rm7/%5Bdev%5D-Jumpu-UI-%7C-Tailwind-CSS-Components-%26-Design-System?node-id=420%3A613

こちらに貼りました、編集権限付与します。

**Comment by knokmki612** [comment]
ありがとうございます :pray:

**Comment by Hidetaro7** [comment]
Faviconもないので、アイコンとしてどうするかも考えたほうがいいかも

**Comment by knokmki612** [comment]
風的なもので修飾したいと思ったので点を風に見立ててみたのですがどうなんでしょうね
直線より曲線のシルエットの方がたなびいている感じがでていいのかなと思いました

あとアイコンも試してみましたが（自分の想像力の範囲だと）いまいちまとまらない感じがしました。しいていえばFrame 4がましかなとおもいました（文字が多いので縮小時の視認性がよくない印象）

Figmaは編集権限いただいていましたが教育関係向けの設定なのか、教育アカウントの申請しないと編集できない状態でした。ひとまず複製して編集しました

![image](https://user-images.githubusercontent.com/9744580/175251638-89193a53-f0c3-4f1e-b2a2-2771c6f6ce38.png)

![image](https://user-images.githubusercontent.com/9744580/175264717-30b87241-ff82-46a3-8290-abc92f81d451.png)

![image](https://user-images.githubusercontent.com/9744580/175262144-996e39a6-f085-4e63-bab9-06b1e6d5c581.png)

![image](https://user-images.githubusercontent.com/9744580/175264384-965e9219-20d7-4d66-9e7d-7eab5d00f5d8.png)

**Comment by Hidetaro7** [comment]
アイコンのほうがよさそうな気がしてきました。
アイデアとしてはどれも面白いです。

Frame 4は[アサヒビール本社社屋の屋上のオブジェ](https://www.google.com/search?q=%E3%82%A2%E3%82%B5%E3%83%92%E3%83%93%E3%83%BC%E3%83%AB%E6%9C%AC%E7%A4%BE%E7%A4%BE%E5%B1%8B%E3%81%AE%E5%B1%8B%E4%B8%8A%E3%81%AE%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7&sxsrf=ALiCzsb5a_JncUS1SZFNvRd-ubCjXdqtpQ:1656029306525&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiR9rX05cT4AhVKm1YBHXRtDFUQ_AUoAXoECBwQAw&biw=1210&bih=953&dpr=2)を思い出しました。

**Comment by Tomo416** [comment]
どれもいいですね😃
Frame4は風を受けている船の帆にも見えます！

**Comment by knokmki612** [comment]
単体のアイコンで考えたもの共有します

縦のアラインどうするといいのかとかあると思いますので、これもあくまでドラフトです

![image](https://user-images.githubusercontent.com/9744580/176372445-b7e36cec-edc1-49e9-8751-fb6aae871098.png)

Duplicateして作業したもの
https://www.figma.com/file/Rbio8PZWNzIka9kh2QQpuU/%5Bdev%5D-Jumpu-UI-%7C-Tailwind-CSS-Components-%26-Design-System-(Copy)?node-id=420%3A613

**Comment by Tomo416** [comment]
個人的にも「じゅんぷう」と聞いたときに、今あげていただいている船と帆の絵のイメージは強いです。

**Comment by knokmki612** [comment]
ちょっと具体的過ぎましたかね、たしかにそうかもしれないです

**Comment by Tomo416** [comment]
いいと思いました！
フォントがまるっぽいので、これを、丸っぽいテイストにするのもありかな
手書きでちょっと書いてみました

![Image](https://user-images.githubusercontent.com/57510486/176374284-3f171320-6eb8-47f3-9d85-d6b06ff922ab.PNG)

**Comment by Hidetaro7** [comment]
> 単体のアイコンで考えたもの共有します
> 
> テキストとアイコンの縦のアラインどうするといいのかとかあると思いますので、これもあくまでドラフトです
> 
> ![image](https://user-images.githubusercontent.com/9744580/176372445-b7e36cec-edc1-49e9-8751-fb6aae871098.png)
> 
> Duplicateして作業したもの https://www.figma.com/file/Rbio8PZWNzIka9kh2QQpuU/%5Bdev%5D-Jumpu-UI-%7C-Tailwind-CSS-Components-%26-Design-System-(Copy)?node-id=420%3A613

アイコンの可読性（潰れないか？丸みをフォントに近づけられるか？）を再チェックしてOKにしようという話になった。

**Comment by Hidetaro7** [comment]
ロゴにするにはちょっと細いと思ったので少し太くしました。得に小さくしてもこのせいで潰れたりしないように見えるので、この方向でいきたいと思います。

![Image](https://user-images.githubusercontent.com/281424/182531470-a2d7bc98-f554-4c11-ae62-7f1dd70f04da.png)

**Comment by knokmki612** [comment]
変更そのものに異論ないですが、シンボルマークとロゴタイプの縦の位置について、Jが小文字のようにベースラインの下にはみ出ているように私は感じるのですが、
個人的にはシンボルマークをベースラインより上までずらすとよりよいような気がしました

**Comment by Hidetaro7** [comment]
![Image](https://user-images.githubusercontent.com/281424/182537407-acf025c3-9f05-4e32-b10c-e8c3ae004735.png)

いいかも

**Comment by knokmki612** [comment]
このシンボルマーク、ロゴタイプでよさそうということで完了
