### ISSUE TITLE
{Labeled,}LikeButton: 他のコンポーネントと比べると再利用性が低い気がする

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#181]
関連 https://github.com/tuqulore/jumpu-ui/issues/61

いいね！、あるいはお気に入りボタンそのものは確かに色々なサービスで使われているが、Jumpu UIの提供するコンポーネントとしては他のボタン、タブなどと比べると利用場面が限定される印象がある。

どちらかというと用途に縛られず見た目にフォーカスした（テキストラベルつきのバリエーションも提供可能な）OutlinedIconButton　が必要という気がした。

アイコンがハードコーディングされていることも再利用性という観点では改善の余地があるように思う。
たとえばいいね！ボタンをブックマークボタンにすることが容易ではない、のような問題があるように思う。

**Comment by Hidetaro7** [comment]
確かに当初は考えが及ばなかったが、Likeというアクションには、年齢や性別をまたぐと使いづらい（特にビジネスシーン）という声がクライアントワークで聞かれたので、指摘の通り利用場面が限られると思う。

> どちらかというと用途に縛られず見た目にフォーカスした（テキストラベルつきのバリエーションも提供可能な）OutlinedIconButton　が必要という気がした。

そのとおりな気がする。

**Comment by knokmki612** [comment]
ひとまず LabeledLikeButton 、 LikeButton については廃止という方針になった

代わりの見た目のコンポーネントが必要かどうかは別途検討
