### ISSUE TITLE
Modal Dialogコンポーネントの実装

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#182]
dialog要素が利用可能なので、ブラウザによってデフォルトで提供されるインタラクションを補完する見た目として、 Dialog コンポーネントクラスの実装が可能かと思った。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/dialog

**Comment by Hidetaro7** [comment]
Figma版 Modal UI を公開した
https://www.figma.com/community/file/1042706969451783914

名称はDialogにしようかとも思うが決めきれない

**Comment by knokmki612** [comment]
> 名称はDialogにしようかとも思うが決めきれない

Modalが慣習的にダイアログのことを指し示すことは理解しているのですが、ModalはModelessと対比する関係の言葉でもあり、極端なことを言えばボタンも一種のモーダルなUIと言えます。作ろうとしているものを指し示す言葉を正確にするとModal Windowなのかもしれません。
Dialogも本来的な言葉の意味としては対話のことを指しますから、Dialogについても慣習的な言葉の用法がされている気がしますね。こちらはこちらで言葉を正確にするとDialog Boxかもしれません。

その上で、ModalとDialogのどちらを言葉づかいとして選ぶのがいいかについてですが、このUIが必要な場面は、なにかユーザーに確認をとりたいような場面だと私は思うわけです。
そうすると、確認をとりたいような時に使うということが分かる言葉づかいは、Dialog（対話）する○○のような感じなのかなと思いました。

たぶんこのあたりのUIの用語の歴史的変遷はひでさんのほうが詳しいような気もするのでご意見伺いたいです。

**Comment by Hidetaro7** [comment]
参考になる記事 https://u-site.jp/alertbox/modal-nonmodal-dialog

**Comment by Hidetaro7** [comment]
簡単に整理すると

モーダル = 現在のタスクから違った状態（モード）に入ること
ダイアログ = 確認や対話を求めること

このことから双方の目的に使われることは今作ろうとしているUIにどちらも当てはまるケースがあると考えられる。
そういう意味では ModalDialog が適切だろう。

画面中央以外に配置されやすい非モーダル ot モードレス という意味での使い方もできなくはない。
が、常に表示しつつ現状のタスクと別モードのタスクを相互行き来しかつ対話できるという非モーダルな性質のもとと、画面中央にどんと表示されるモーダルダイアログの見た目や性質とは概ね異なるはず。

だからあくまで今回つくるモーダルダイアログは画面中央に表示させるものがデフォルトスタイルとして定義するとよい。

アンチパターンではあるが、この手のモーダルやダイアログの見た目や機能を利用して、よく広告とか会員登録とか、現在のモード（ここでは関心と定義づけ）とは関連が低い内容でユーザーの行動を阻害し、認知負荷を高めるようなデザインを見かけるが、これはデザインの理念に反するものとしてツクロア UI design knowhowやJumpu UIでもドキュメントするとよい。

**Comment by knokmki612** [comment]
モーダルでないダイアログもあるということで理解しました。

その場合のモーダルなダイアログの要件ってどんなところにあるのかが気になってきています

画面全体にオーバーレイして中央配置される点だけでしょうか

**Comment by Hidetaro7** [comment]
> 画面全体にオーバーレイして中央配置される点だけでしょうか

閉じるボタンが右上にあるまでは要件に含めたいと思います。それくらいでよいかと思ってましたが他に思い当たる要件はありますか？

どうつくっていくかは相談ですが、dialog要素の効果をStorybook上でJSからの関数呼び出しによって ::backdrop 疑似要素が表示される（逆に言えばJSの呼び出しがないと見た目が確認できない）ので、それをどうやって見せるか、ちょっと判断つかないです。

ダイアログである以上、「実行」「キャンセル」のボタンが配置できるようなつくりにするべき、バリエーションとして含めるか？ギャラリーに含めるか？ ご意見をいただけたらと思います。

**Comment by knokmki612** [comment]
モーダルとしての振る舞いに、例えばビューポートに対して `overflow: hidden` を付与してスクロールできなくするなどもあるように思います。
ようするに今話が出てきているJSによる振る舞いの実装もモーダルである要件に含まれてくるような気がするので、このあたりはドキュメンテーションされている必要があるかなと思いました。

> ダイアログである以上、「実行」「キャンセル」のボタンが配置できるようなつくりにするべき、バリエーションとして含めるか？ギャラリーに含めるか？

閉じるボタン以外のボタンがないダイアログはもはやポップアップウィンドウと呼びたい気もしますが、しかしボタンがなくとも画面を占有してメッセージを表示するというだけでもダイアログ的な見た目の提示と言えるような気もします。
また、実装としてはボタンの配置などはTailwindCSSユーティリティで実装者に委ねたいという気持ちもあるので、ひとまずボタンの配置まではコンポーネントにスタイルする必要はない気がします。

**Comment by Hidetaro7** [comment]
> ボタンの配置まではコンポーネントにスタイルする必要はない気がします。

承知です、それでよいと思いました。

**Comment by knokmki612** [comment]
名称としてはModal Dialogでいいのではという話になった

**Comment by Hidetaro7** [comment]
Storybook 側で Modal Dialog に変更した

**Comment by Hidetaro7** [comment]
方針が決まったので完了

**Comment by Hidetaro7** [comment]
実装までがissueなので完了を取り下げる

**Comment by knokmki612** [comment]
> モーダルダイアログの振る舞いについては `@headlessui` のDialogを使用してもらい、見た目については `jumpu-card` `jumpu-button` `jumpu-icon-button` を使ってもらう（つまりmodalDialogとしてのコンポーネントの定義は不要ではないか）という気がしてきました

_Originally posted by @knokmki612 in https://github.com/tuqulore/jumpu-ui/pull/266#pullrequestreview-1130805474_

上記から、コンポーネントとしては実装せず、ギャラリーに実装例を用意する方針に変更した
