### ISSUE TITLE
ボーダーカラーをカスタマイズ可能にする

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#243]
関連 #231 

現状gray-50をボーダーカラーとして使用しているがコントラストが十分でないのではとフィードバックがあった。

より濃い色に差し替えるとともに、

`colors.border` のようなセマンティックな色名とともにボーダーカラーをカスタマイズ可能にするといいのではという話になった。

**Comment by Hidetaro7** [comment]
現状

![Image](https://user-images.githubusercontent.com/281424/191885266-c206a248-afd5-4c85-82bd-257a070fb24c.png)

`border: colors.gray[300]` くらいがちょうど良さそう

![Image](https://user-images.githubusercontent.com/281424/191885197-bd6a095f-1ccc-448a-8479-0670ecff087a.png)

**Comment by Hidetaro7** [comment]
- 例えば a要素の場合で hover したときにボーダーカラーがちょっと暗くなるとかしたい場合どうするか
- 他にデフォルトスタイルとして含めるべきと考えられるコンポーネント
  - Forms/input
  - Forms/textarea
  - Forms/select
  - Tag
  - BoxedTabs
  - Tabs

**Comment by Hidetaro7** [comment]
> ちょっと暗くなるとかしたい場合どうするか

https://tailwindcss.com/docs/theme#core-plugins

ここに書いてあるように `DEFAULT` 値を設定してバリエーションをはやしてみたかったが、なぜか反映されなかった。

**Comment by knokmki612** [comment]
> バリエーションをはやしてみたかった

ひととおりみたが考えられるバリエーションは、デフォルト、とより濃いもの（ダーク）の2種類ではという話になった

https://tuqulore.github.io/jumpu-ui/?path=/docs/status-tag--default-story

**Comment by Hidetaro7** [comment]
ボーダーカラーのバリエーションは今後のアップデートで検討するで良いかもしれません。
少なくとも破壊的な変更にならないように思えますので。

**Comment by knokmki612** [comment]
> ここに書いてあるように `DEFAULT` 値を設定してバリエーションをはやしてみたかったが、なぜか反映されなかった。

https://tailwindcss.com/docs/customizing-colors#color-object-syntax を見る分には DEFAULT キーが設定可能に見えますが、なんででしょうね

border-color ユーティリティクラスが存在するので、色名を独自に定義するというよりもこちらの初期値を変更し参照するのがいいように思えてきました

https://tailwindcss.com/docs/border-color

https://github.com/tailwindlabs/tailwindcss/blob/011de9b6b6ebaa2013c20bee58ec27770f2acbd8/stubs/config.full.js#L81-L84

**Comment by Hidetaro7** [comment]
> 色名を独自に定義するというよりもこちらの初期値を変更し参照

ボーダーカラーのデフォルト値を設けることで余計に管理コストが増えることより、初期値をgray-300あたりに変更する程度にとどめたほうが良い気がしてきました。
