### ISSUE TITLE
`Status/Tag`がStorybookに含まれていないように見える

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/jumpu-ui#247]
似た仲間の `Status/FilledTag` はStorybookに表示されるが、なぜか `tag` だけ含まれていない。

**Comment by knokmki612** [comment]
https://github.com/tuqulore/jumpu-ui/commit/113ea4879aa0dfd8b9d4a6b260c10598ca3fe152 時点の Storybook https://tuqulore.github.io/jumpu-ui/ をみる限りTagのStorieファイルの表示に失敗しているように思います

> Unexpected error while loading ./Tag.stories.mdx: Module build failed (from /home/runner/work/jumpu-ui/jumpu-ui/node_modules/babel-loader/lib/index.js):
> SyntaxError: /home/runner/work/jumpu-ui/jumpu-ui/packages/tailwindcss/stories/Tag.stories.mdx: Identifier 'anchor' has already been declared. (168:13)
> 
>   166 | closable.parameters = { storySource: { source: 'html`\n      <div class=\"jumpu-tag\">\n        デフォルト\n        <div role=\"button\" aria-label=\"閉じる\" />\n      </div>\n    `' } };
>   167 |
> > 168 | export const anchor = () => (
>       |              ^
>   169 |           html`
>   170 |       <a href="#" class="jumpu-tag ">
>   171 |         デフォルト
>     at instantiate (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:72:32)
>     at constructor (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:366:12)
>     at Object.raise (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3453:19)
>     at ScopeHandler.checkRedeclarationInScope (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3645:19)
>     at ScopeHandler.declareName (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3611:12)
>     at Object.declareNameFromIdentifier (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12285:16)
>     at Object.checkIdentifier (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12280:12)
>     at Object.checkLVal (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12206:12)
>     at Object.parseVarId (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:15533:10)
>     at Object.parseVar (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:15507:12)
>     at Object.parseVarStatement (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:15310:10)
>     at Object.parseStatementContent (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:14852:21)
>     at Object.parseStatement (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:14777:17)
>     at Object.parseExportDeclaration (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:16157:17)
>     at Object.maybeParseExportDeclaration (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:16103:31)
>     at Object.parseExport (/home/runner/work/jumpu-ui/jumpu-ui/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:16030:29)
>  ./stories/Tag.stories.mdx@https://tuqulore.github.io/jumpu-ui/main.fe0935f4.iframe.bundle.js:1:342032
> __webpack_require__@https://tuqulore.github.io/jumpu-ui/runtime~main.7f9bf59e.iframe.bundle.js:1:1301
> webpackContext@https://tuqulore.github.io/jumpu-ui/main.fe0935f4.iframe.bundle.js:1:52846
> ../../node_modules/@storybook/html/dist/esm/client/preview/index.js/executeLoadableForChanges/</<@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:889613
> ../../node_modules/@storybook/html/dist/esm/client/preview/index.js/executeLoadableForChanges/<@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:889562
> executeLoadable@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:889528
> executeLoadableForChanges@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:890380
> getProjectAnnotations@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:894876
> ../../node_modules/synchronous-promise/index.js/_runResolutions/<@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:1860141
> _runResolutions@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:1860082
> then@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:1857538
> getProjectAnnotationsOrRenderError@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:820825
> initialize@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:819788
> configure@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:895518
> configure@https://tuqulore.github.io/jumpu-ui/vendors~main.06e0763e.iframe.bundle.js:2:896200
> ./generated-stories-entry.js/<@https://tuqulore.github.io/jumpu-ui/main.fe0935f4.iframe.bundle.js:1:50006
> ./generated-stories-entry.js@https://tuqulore.github.io/jumpu-ui/main.fe0935f4.iframe.bundle.js:1:50298
> __webpack_require__@https://tuqulore.github.io/jumpu-ui/runtime~main.7f9bf59e.iframe.bundle.js:1:1301
> 0@https://tuqulore.github.io/jumpu-ui/main.fe0935f4.iframe.bundle.js:1:366513
> __webpack_require__@https://tuqulore.github.io/jumpu-ui/runtime~main.7f9bf59e.iframe.bundle.js:1:1301
> checkDeferredModules@https://tuqulore.github.io/jumpu-ui/runtime~main.7f9bf59e.iframe.bundle.js:1:957
> webpackJsonpCallback@https://tuqulore.github.io/jumpu-ui/runtime~main.7f9bf59e.iframe.bundle.js:1:645
> @https://tuqulore.github.io/jumpu-ui/main.fe0935f4.iframe.bundle.js:1:47
> vendors~main.06e0763e.iframe.bundle.js:2:201993
>
