### ISSUE TITLE
Tabs でマウスボタンを押下したときの背景色が出てこない

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/jumpu-ui#274]
Tabs で `aria-selected=true` だけが押下時反応し、それ以外が反応しないが、むしろ逆の効果がほしいと思った。

**Comment by knokmki612** [comment]
> 以下にTabsを使用している環境を用意したので、破綻するケースについてサンプルをいただけますでしょうか
> 
> https://play.tailwindcss.com/E52RyBPopc

_Originally posted by @knokmki612 in https://github.com/tuqulore/jumpu-ui/issues/273#issuecomment-1319502680_

と同様に現在の状況どういう問題があって、なにを解決すべきかについてコードベースで確認できるようなものを用意してもらえると助かります。

**Comment by Hidetaro7** [comment]
コードベースだと現状難しいので解決したいことを列挙

1. aria-selected="false" を押した時に背景色が表示される
2. aria-selected="true" を押したときは背景色は表示されない（反応しない）
3. aria-selected="false" ではborder-bottomは表示しない
4. 3.を行うとテキストラベルが1px垂直方向にズレる、そのため一案だが aria-selected="true" の下線は疑似要素で `position: absolute` 等による配置などでずれないようにしたい

**Comment by knokmki612** [comment]
> 押下時反応し、それ以外が反応しない

`:active` 擬似クラスが要素に対して適用されるようなケースということで理解しました。
以下スクリーンレコードにしました。
https://user-images.githubusercontent.com/9744580/214453520-c092c573-f78b-403e-89d2-831daa773661.mp4

> 1. aria-selected="false" を押した時に背景色が表示される
> 2. aria-selected="true" を押したときは背景色は表示されない（反応しない）

これは逆のことを言っていますかね？つまり

1. aria-selected="true" を押した時に背景色が表示される
2. aria-selected="false" を押したときは背景色は表示されない（反応しない）

という状態かと思うのですがいかがでしょうか。

対処としてはaria-selected="false" を押したときについても背景色を表示するような変更をおこなうことが考えられますがいかがでしょうか。

> aria-selected="false" ではborder-bottomは表示しない
> 3.を行うとテキストラベルが1px垂直方向にズレる、そのため一案だが aria-selected="true" の下線は疑似要素で position: absolute 等による配置などでずれないようにしたい

こちらについては #273 で取り扱っている内容かと思うのでそちらで議論できればと思います
