### ISSUE TITLE
labelに対するスタイルはサポートしない

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/jumpu-ui#34]
なぜしないのか？その理由をドキュメンテーションする。

- 状況によっていくつかのスタイルを使い分ける必要がある、例えば名前のフィールドと複数のチェックボックスだとレイアウトが異なる
- コンセプトとして、デザイナーがある程度意図としているスタイルを付与できるためのフレームワークである、そのため、label要素を強制的にスタイルで縛るのはコンセプトに合致しない
- 他のフレームワークとの差別化という意味でも、開発者がこのフレームワークを選ぶか選ばないかという判断がしやすくなる

といった理由が上げられる。

**Comment by knokmki612** [comment]
現状としては `Forms/Label` のストーリーを作成し、labelの見た目はJumpu UIとしては提供しない旨をドキュメンテーションするのがいいと思った

**Comment by Hidetaro7** [comment]
> 現状としては `Forms/Label` のストーリーを作成し、labelの見た目はJumpu UIとしては提供しない旨をドキュメンテーションするのがいいと思った

この方針で、サポートしない理由をそのページに記載する。
理由内容についてはこのissueの冒頭の3つの理由を列挙、書きっぷりは再考する。
