### ISSUE TITLE
タグをクリッカブルにした場合のバリアント

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#346]
> クリッカブルにした場合のバリアントが必要になった気がするのですが、ひとまず別途対応でも良いかと思いましたのでおまかせします。

_Originally posted by @knokmki612 in https://github.com/tuqulore/jumpu-ui/pull/293#pullrequestreview-1292338933_

**Comment by knokmki612** [comment]
どちらかというとクリッカブルな要素へのスタイルを追加するのが妥当という気がしました

例

`:is(button, a, [role="button"]): hover { ... }`

**Comment by Hidetaro7** [comment]
#401 と重複しているのでクローズ
