### ISSUE TITLE
Tailwind CSS Colors に 950 が追加されていた

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/jumpu-ui#369]
https://tailwindcss.com/docs/customizing-colors

JUMPU UIでも反映するべきかと思う。

**Comment by knokmki612** [comment]
Jumpu UI で独自に定義している色は以下になります。いずれも単色50~900番は提供しておらず単一色のみです。
反映するべき箇所は存在しますでしょうか

https://github.com/tuqulore/jumpu-ui/blob/ef0e641330bd8e3b186853dd02affbcd6b1e61ff/packages/tailwindcss/colors.js#L1-L5

**Comment by Hidetaro7** [comment]
Figma の修正が必要なので行う。
コードで変更する場面は今のところ考えられないと思う。

**Comment by Hidetaro7** [comment]
手元のほうで 950 を入れておいた。
