### ISSUE TITLE
Tag をクリッカブルな要素に対して使用した場合はクリッカブルな見た目を提供する提案

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#401]
関連 https://github.com/tuqulore/jumpu-ui/issues/280

現状クリッカブルな見た目をTagとして提供するのは廃止しているが、たとえば以下のようなスタイルを追加することで使用するユーティリティクラスを減らせるのではないかという提案

> どちらかというとクリッカブルな要素へのスタイルを追加するのが妥当という気がしました
> 
> 例
> 
> `:is(button, a, [role="button"]):hover { ... }`

_Originally posted by @knokmki612 in https://github.com/tuqulore/jumpu-ui/issues/346#issuecomment-1541738466_

**Comment by Hidetaro7** [comment]
なるほど、is擬似クラスによるインタラクティブ要素への指定は良いと思いました👍
