### ISSUE TITLE
{Labeled,}LikeButton: いいねがアクティブになっているように認識しづらい

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#61]
> いいねが有効の際のみせかたは検討したほうがいいのか気になりました

Likedというバリアントで表現されていたのですでに実装としては存在していますね
いいねがアクティブになっているように認識できていなかった、という話でしょうか(デザインにおける指摘)

_Originally posted by @knokmki612 in https://github.com/tuqulore/tuqulore-ui/issues/54#issuecomment-918721668_

**Comment by Hidetaro7** [comment]
廃止となったが、icon-button で再現するとなれば、トグルという機能が提供されていない。
おそらく aria-pressed 属性などでコントロールするのだろうか。

**Comment by knokmki612** [comment]
> ひとまず LabeledLikeButton 、 LikeButton については廃止という方針になった
> 
> 代わりの見た目のコンポーネントが必要かどうかは別途検討

_Originally posted by @knokmki612 in https://github.com/tuqulore/jumpu-ui/issues/181#issuecomment-1271120842_
      
したがって対応しない。
