### ISSUE TITLE
バリアブルでSpacing Scaleを管理する

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#617]
[バリアブルをデザインに適用する – Figma Learn - ヘルプセンター](https://help.figma.com/hc/ja/articles/15343107263511-%E3%83%90%E3%83%AA%E3%82%A2%E3%83%96%E3%83%AB%E3%82%92%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%AB%E9%81%A9%E7%94%A8%E3%81%99%E3%82%8B)によれば、数字バリアブルはパディングで使用可能

Spacing: [Customizing Spacing - Tailwind CSS](https://tailwindcss.com/docs/customizing-spacing)

**Comment by Hidetaro7** [comment]
関連 https://github.com/tuqulore/jumpu-ui/issues/596

すでにspacing のkey: value はこのブランチで設定しています。
https://www.figma.com/design/Lo0RCwldNBkcYFnl075Rm7/branch/uGeitaFPy5pd0ddbkgoVL0/Jumpu-UI-%7C-Tailwind-CSS-Components?m=auto&node-id=105-65&t=5uM1YCBJapn7GNyK-1

**Comment by Hidetaro7** [comment]
そのプロパティに適したデータ型のみ扱える

```
たとえば、数値バリアブルを角の半径にスコープした場合、そのバリアブルを適用できるのは角の半径だけです。このバリアブルは、他のサポートされているプロパティのオプションとしては表示されません。
```

https://help.figma.com/hc/ja/articles/15145852043927-%E3%83%90%E3%83%AA%E3%82%A2%E3%83%96%E3%83%AB%E3%81%AE%E4%BD%9C%E6%88%90%E3%81%A8%E7%AE%A1%E7%90%86#h_01H32HZB74TE7MJXYBWEBBQWJV

**Comment by knokmki612** [comment]
範囲設定をしていたということですかね？(たぶん)

**Comment by Hidetaro7** [comment]
そうですね

<img width="631" alt="image" src="https://github.com/user-attachments/assets/4f173df5-04ef-4490-a147-44552f69ed8d">

**Comment by Hidetaro7** [comment]
レビュー依頼を出しました。 @knokmki612

**Comment by knokmki612** [comment]
> 関連 #596
> 
> すでにspacing のkey: value はこのブランチで設定しています。 https://www.figma.com/design/Lo0RCwldNBkcYFnl075Rm7/branch/uGeitaFPy5pd0ddbkgoVL0/Jumpu-UI-%7C-Tailwind-CSS-Components?m=auto&node-id=105-65&t=5uM1YCBJapn7GNyK-1

マージ済み
