### ISSUE TITLE
Card: Anchorであるときに必要に応じてdisplayプロパティ付与してほしい

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#97]
`display: flex`などにする可能性もあるので、デフォルトにdisplayプロパティを含めるのはスタイルの上書きが多く発生する可能性もあるため、持たせない。

つまりcardをa要素でマークアップする場合、必要に応じて`block`や`flex`をクラスに記述する。

_Originally posted by @Hidetaro7 in https://github.com/tuqulore/tuqulore-ui/pull/85#discussion_r737055937_

**Comment by Hidetaro7** [comment]
> Anchorであるときに必要に応じてdisplayプロパティ付与してほしいことをドキュメンテーションする

こちらの方針で。
